{
 "title": "AKS Security",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(node) (kube_node_status_condition{cluster=\"aks-ecns-cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=\"nginx-reverse-proxy-7f6ff76d9f-rsp6s\"} == 1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_status_phase{pod=\"azure-vote-front-699c95c8dd-l9vt2\"} == 1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_status_phase{pod=\"azure-vote-back-5b548464f5-4j6tg\"} == 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(pod) (container_cpu_usage_seconds_total{pod=~\"nginx-reverse-proxy-7f6ff76d9f-rsp6s|azure-vote-front-699c95c8dd-l9vt2|azure-vote-back-5b548464f5-4j6tg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{pod=~\"nginx-reverse-proxy-7f6ff76d9f-rsp6s|azure-vote-front-699c95c8dd-l9vt2|azure-vote-back-5b548464f5-4j6tg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Receive",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (container_network_receive_bytes_total{pod=~\"nginx-reverse-proxy-7f6ff76d9f-rsp6s|azure-vote-front-699c95c8dd-l9vt2|azure-vote-back-5b548464f5-4j6tg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Transmit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (container_network_transmit_bytes_total{pod=~\"nginx-reverse-proxy-7f6ff76d9f-rsp6s|azure-vote-front-699c95c8dd-l9vt2|azure-vote-back-5b548464f5-4j6tg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_packets_dropped_total{pod=~\"nginx-reverse-proxy-7f6ff76d9f-rsp6s|azure-vote-front-699c95c8dd-l9vt2|azure-vote-back-5b548464f5-4j6tg\"}) + sum(container_network_transmit_packets_dropped_total{pod=~\"nginx-reverse-proxy-7f6ff76d9f-rsp6s|azure-vote-front-699c95c8dd-l9vt2|azure-vote-back-5b548464f5-4j6tg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Policies",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "kube_networkpolicy_annotations{namespace=\"default\"}",
     "legendFormat": "{{networkpolicy}}"
    }
   ]
  }
 ]
}